### ISSUE TITLE
Could you please share the file for imagenet100 subsets of 5% and 25%

### ISSUE THREAD

**Issue by rokmr** [kangzhiq/NNCSL#2]

**Comment by kangzhiq** [comment]
Hi again!

Here there are:
**percent0.25** are for 25% and **percent0.05** are for 5%. Here I am using seed 0, you can easily generate other files with the file provided in the repository.
[spc.325_percent0.25_split0.txt](https://github.com/kangzhiq/NNCSL/files/14370814/spc.325_percent0.25_split0.txt)
[spc.325_percent0.25_split0_cls.txt](https://github.com/kangzhiq/NNCSL/files/14370815/spc.325_percent0.25_split0_cls.txt)
[spc.65_percent0.05_split0.txt](https://github.com/kangzhiq/NNCSL/files/14370816/spc.65_percent0.05_split0.txt)
[spc.65_percent0.05_split0_cls.txt](https://github.com/kangzhiq/NNCSL/files/14370817/spc.65_percent0.05_split0_cls.txt)

**Comment by rokmr** [comment]
Thank you

**Comment by rokmr** [comment]
It was helpful. :)
