### ISSUE TITLE
please share the link of imagenet100which you have used.

### ISSUE THREAD

**Issue by rokmr** [kangzhiq/NNCSL#3]

**Comment by kangzhiq** [comment]
Hi!

Thanks for your interest in our work!! And sorry for the late response! I have been super busy recently...

If I am not mistaken, we were using the dataset downloaded from Kaggle [This link](https://www.kaggle.com/datasets/ambityga/imagenet100/data?select=train.X1). Please let me know if you need further instructions!

Best,
Zhiqi

**Comment by rokmr** [comment]
Thank you

**Comment by rokmr** [comment]
Thank you!
